; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = cosmosdevboard

[common]
default_src_filter = +<src/*>
build_flags = -DDEBUG=1
lib_deps =
    SPI
    Wire

[env:cosmosdevboard]
platform = espressif32
board = cosmosdevboard
framework = arduino
lib_deps = ${common.lib_deps}
